### ISSUE TITLE
 Incorrect import of the qlik module 

### ISSUE THREAD

**Issue by mindspank** [LorisLombardo87/qs-side-menu#5]
Hey,

This project incorrectly imports the `qlik` module as `js/qlik` which will fail in June 2018 of Qlik Sense.
Please see the documentation here: https://help.qlik.com/en-US/sense-developer/April2018/Subsystems/Extensions/Content/Howtos/call-qlik-library.htm

**Comment by LorisLombardo87** [comment]
should be correct now!
