### ISSUE TITLE
Scrolling complete page while scrolling filters from Side Menu.

### ISSUE THREAD

**Issue by sbhagana** [LorisLombardo87/qs-side-menu#6]
Issue is occurring while using it in Mashups,

While scrolling inside Filters for scroll down filter values, it just scroll down complete dashboard in background and scroll complete filter body with dashboard. 

** It should not scroll complete html body while I am scrolling filters values from Side Menu.

**Comment by LorisLombardo87** [comment]
hi sbhagana, you should not use this in mashups.
but maybe you can grab some code and use it in your mashup like a "normal" piece of code.
